services:
  next-app:
    build: .
    container_name: next-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/app_db
      SESSION_SECRET: practice-project-session-secret
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres-15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

    migrate:
      build: .
      container_name: prisma-migrate
      command: sh -c "npx prisma migrate deploy"
      environment:
        DATABASE_URL: postgresql://postgres:postgres@postgres:5432/app_db
      depends_on:
        postgres:
          condition: service_healthy
      restart: "no"

volumes:
  postgres_data: